### ISSUE TITLE
Namespace issue: typo with bpm_clear_stubbornness

### ISSUE THREAD

**Issue by 42nevin** [Better-Politics-Mod/Better-Politics-Mod-Vic-3#167]
I found this typo during a play in combination with Economic & Financial mod, whose variables get cleared at the end of each month.

Solution:
Change bpm_clear_stubborness_utils.3 to bpm_clear_stubbornness_utils.3 in
https://github.com/Better-Politics-Mod/Better-Politics-Mod-Vic-3/blob/main/better-politics-mod/events/bpm_ig_utils/bpm_clear_stubborness.txt
and
https://github.com/Better-Politics-Mod/Better-Politics-Mod-Vic-3/blob/main/better-politics-mod/common/on_actions/BPM_code_on_actions.txt

**Comment by xxxAnn** [comment]
Fixed by 73f1197
